### ISSUE TITLE
Update for SWAP

### ISSUE THREAD

**Issue by berkenvr** [tile-lang/tile-vm#37]
There is a meaningless usage of SWAP opcode.

First of all, swap works like that:
Lets say user enter that command SWAP 5 that means swap gonna take top element of stack and change the position with element which is index 5 (start counting from zero). 
This is work fine, but user can try SWAP 0 command which is swap top element with top element. Our machine is not check it for now, this is not a error, just a meaningless operation. 

Maybe we should change the swap operation to check it. Maybe we can throw an exception.

**Comment by yasinxdxd** [comment]
It is the subject of optimization you can do this in c:
if (true == true) { }
but this code compiles succesfully, no exception or something. Optimizer will not create a branching jump statement for your if statement. If somebody writes swap 0, we won't translate that line of code as a bytecode if we have our optimizer in the future.
